### ISSUE TITLE
Malware / Virus

### ISSUE THREAD

**Issue by Vanity6969** [ihatepythonXD/valosharp_cracked#1]
Please don't download it's a malware input into the code. Stop ratting other people u dumbfuck

**Comment by ihatepythonXD** [comment]
proof? 
the source is the .py the pyc is python bytecode if you have half a brain you can check and see that it isnt malware

**Comment by Vanity6969** [comment]
I checked it you moron and it has malware stop lying u spastic

**Comment by ihatepythonXD** [comment]
send proof then :P
