### ISSUE TITLE
VIRUS

### ISSUE THREAD

**Issue by NicolasM9999** [ihatepythonXD/valosharp_cracked#2]
DONT DOWNLOAD ITS A TROJAN/MALWARE !!!!!

**Comment by ihatepythonXD** [comment]
🤣 mad your tool is cracked? 
doing this just makes it more fun for me
like i said to the last dude the py file is source just read it
and the pyc is python bytecode if u have half a brain u can read it

**Comment by ihatepythonXD** [comment]
post more and ill fully deobf the source and make proof the code / bytecode isnt a virus

**Comment by NicolasM9999** [comment]
Malware! DONT DOWNLOAD
